from io import BytesIO

from openpyxl import Workbook

from file_normalization import normalize_drive_file


def test_normalize_drive_file_converts_apple_xlsx_to_canonical_csv():
    result = normalize_drive_file(
        provider="apple",
        sales_yyyymm="202604",
        file_name="Apple202604数理集計後_ICE納品.xlsx",
        mime_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        data=_apple_workbook_bytes(),
    )

    assert result["file_name"] == "Apple202604数理集計後_ICE納品.csv"
    assert result["content_type"] == "text/csv; charset=utf-8"
    assert result["format"] == "csv"
    assert result["was_converted"] is True
    assert result["columns"][:6] == [
        "sales_yyyymm",
        "start_date",
        "end_date",
        "upc",
        "isrc_isbn",
        "vendor_identifier",
    ]
    assert result["header_row_index"] == 1
    assert result["row_count"] == 1
    assert result["data"].decode("utf-8").splitlines()[1].startswith(
        "202604,2026-03-29,2026-05-02,,,standard_1month_ios,27"
    )
    assert "7574.8990455,9354.4734735,海外,MANGA Plus,定期購読" in result["data"].decode("utf-8")


def test_normalize_drive_file_applies_googleplay_cp932_csv_rules():
    result = normalize_drive_file(
        provider="googleplay",
        sales_yyyymm="202604",
        file_name="google202604数理集計後_ICE納品.csv",
        mime_type="text/csv",
        data=_googleplay_csv_bytes(),
    )

    text = result["data"].decode("utf-8")
    assert result["file_name"] == "google202604数理集計後_ICE納品.csv"
    assert result["content_type"] == "text/csv; charset=utf-8"
    assert result["was_converted"] is False
    assert result["columns"][:6] == [
        "sales_yyyymm",
        "description",
        "transaction_date",
        "transaction_time",
        "tax_type",
        "transaction_type",
    ]
    assert result["row_count"] == 1
    assert text.splitlines()[1].startswith(
        "202604,GPA.3300-0017-7281-17473..2,2026-04-06,12:53:11 AM PDT"
    )
    assert "jp.co.shueisha.mangaplus,Subscription,and_standard_mid_1month" in text
    assert "MANGA Plus,定期購読,,1,132,20,112,,,132,0" in text


def test_normalize_drive_file_rejects_unsupported_format():
    try:
        normalize_drive_file(provider="apple", sales_yyyymm="202606", file_name="sales_202606.xls", mime_type=None, data=b"legacy")
    except ValueError as exc:
        assert "unsupported file format" in str(exc)
    else:
        raise AssertionError("expected ValueError")


def _apple_workbook_bytes():
    workbook = Workbook()
    worksheet = workbook.active
    worksheet.append(["Generated by report"])
    worksheet.append(
        [
            "Start Date",
            "End Date",
            "UPC",
            "ISRC/ISBN",
            "Vendor Identifier",
            "Quantity",
            "Partner Share",
            "Extended Partner Share",
            "Partner Share Currency",
            "Sales or Return",
            "Apple Identifier",
            "Artist/Show/Developer/Author",
            "Title",
            "Label/Studio/Network/Developer/Publisher",
            "Grid",
            "Product Type Identifier",
            "ISAN/Other Identifier",
            "Country Of Sale",
            "Pre-order Flag",
            "Promo Code",
            "Customer Price",
            "Customer Currency",
            "通貨",
            "レート",
            "入金額（円）",
            "売上額（円）",
            "国内／海外",
            "アプリ",
            "種別",
            "ID抜粋",
            "JDCN",
            "CP価格",
            "CP",
        ]
    )
    worksheet.append(
        [
            "2026-03-29 00:00:00",
            "2026-05-02 00:00:00",
            None,
            None,
            "standard_1month_ios",
            27,
            6.47,
            174.69,
            "AED",
            "S",
            6467175845,
            None,
            "1month_Standard",
            None,
            None,
            "IAY",
            None,
            "AE",
            None,
            None,
            7.99,
            "AED",
            "AED",
            43.36195,
            7574.8990455,
            9354.4734735,
            "海外",
            "MANGA Plus",
            "定期購読",
            "nth_ios",
            None,
            None,
            None,
        ]
    )
    buffer = BytesIO()
    workbook.save(buffer)
    workbook.close()
    return buffer.getvalue()


def _googleplay_csv_bytes():
    text = (
        "Description,Transaction Date,Transaction Time,Tax Type,Transaction Type,Refund Type,"
        "Product Title,Package ID,Product Type,Sku Id,Hardware,Buyer Country,Buyer State,"
        "Buyer Postal Code,Buyer Currency,Amount (Buyer Currency),Currency Conversion Rate,"
        "Merchant Currency,Amount (Merchant Currency),手数料区分,売上区分,コンテンツ区分,JDCN,"
        "DL数,売上単価,手数料,入金,CP価格,CP,本体価,税\n"
        "GPA.3300-0017-7281-17473..2,Apr 6 2026,12:53:11 AM PDT,,,,"
        "Standard(1 Month) (MANGA Plus by SHUEISHA),jp.co.shueisha.mangaplus,Subscription,"
        "and_standard_mid_1month,,PH,METRO MANILA,,PHP,42.5,2.6353,JPY,112,,"
        "MANGA Plus,定期購読,,1,132,20,112,,,132,0\n"
    )
    return text.encode("cp932")
