from io import BytesIO

from openpyxl import Workbook

from file_normalization import normalize_drive_file


def test_normalize_drive_file_passes_csv_through():
    result = normalize_drive_file(
        provider="apple",
        sales_yyyymm="202606",
        file_name="sales_202606.csv",
        mime_type="text/csv",
        data=b"Transaction Date,SKU,Proceeds\n2026/06/01,book-1,\"1,200\"\n",
    )

    assert result["file_name"] == "sales_202606.csv"
    assert result["content_type"] == "text/csv; charset=utf-8"
    assert result["data"] == b"sales_yyyymm,transaction_date,sku,proceeds_amount\n202606,2026-06-01,book-1,1200\n"
    assert result["format"] == "csv"
    assert result["was_converted"] is False
    assert result["row_count"] == 1


def test_normalize_drive_file_converts_xlsx_to_csv():
    result = normalize_drive_file(
        provider="apple",
        sales_yyyymm="202606",
        file_name="202606_ICE納品.xlsx",
        mime_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        data=_workbook_bytes(),
    )

    assert result["file_name"] == "202606_ICE納品.csv"
    assert result["content_type"] == "text/csv; charset=utf-8"
    assert result["data"] == b"sales_yyyymm,transaction_date,sku,proceeds_amount\n202606,2026-06-01,book-1,1200\n"
    assert result["format"] == "csv"
    assert result["was_converted"] is True
    assert result["columns"] == ["sales_yyyymm", "transaction_date", "sku", "proceeds_amount"]
    assert result["header_row_index"] == 1


def test_normalize_drive_file_rejects_unsupported_format():
    try:
        normalize_drive_file(provider="apple", sales_yyyymm="202606", file_name="sales_202606.xls", mime_type=None, data=b"legacy")
    except ValueError as exc:
        assert "unsupported file format" in str(exc)
    else:
        raise AssertionError("expected ValueError")


def test_normalize_drive_file_applies_googleplay_rules():
    result = normalize_drive_file(
        provider="googleplay",
        sales_yyyymm="202606",
        file_name="sales_202606(その1).csv",
        mime_type="text/csv",
        data=b"Date,Package Name,Product ID,Developer Proceeds\n2026-06-01,jp.example.app,sub_1,900.50\n",
    )

    assert result["data"] == (
        b"sales_yyyymm,transaction_date,package_name,sku,developer_proceeds\n"
        b"202606,2026-06-01,jp.example.app,sub_1,900.50\n"
    )


def _workbook_bytes():
    workbook = Workbook()
    worksheet = workbook.active
    worksheet.append(["Generated by report"])
    worksheet.append(["Transaction Date", "SKU", "Proceeds"])
    worksheet.append(["2026/06/01", "book-1", "1,200"])
    buffer = BytesIO()
    workbook.save(buffer)
    workbook.close()
    return buffer.getvalue()
